### ISSUE TITLE
如何挂载 system.img

### ISSUE THREAD

**Issue by lixianHexin** [wuxianlin/harmonyos_next_emulator_mod#2]
大佬请教个问题，https://wuxianlin.com/2024/10/19/harmonyos-next-code-protect/ 
HarmonyOS Next 应用加密 安全性分析，根据这篇文章，解析出来了 system.img 
但挂载 system.img 一直报下面的错，这个如何处理？

mount: wrong fs type, bad option, bad superblock on /dev/loop0,
missing codepage or helper program, or other error

In some cases useful info is found in syslog - try
dmesg | tail or so.

使用 ./simg2img 转 system.img
报下面的错误
Invalid sparse file format at header magic
Failed to read sparse file

大佬是如何挂载 system.img 的，能教一下吗？

**Comment by wuxianlin** [comment]
试试mount命令加上-t ext4参数

**Comment by lixianHexin** [comment]
还是有问题
[root@VM-4-8-centos hh]# sudo mount -t ext4 -o ro,loop system.img system
mount: wrong fs type, bad option, bad superblock on /dev/loop1,
       missing codepage or helper program, or other error

       In some cases useful info is found in syslog - try
       dmesg | tail or so.

**Comment by wuxianlin** [comment]
file system.img或者fsck.ext4 system.img能识别到ext文件系统信息么？我这里用的ubuntu环境。

**Comment by lixianHexin** [comment]
系统：
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

解析出来的文件：
ubutu:~/hongmeng_20241202/update_packaging_tools/out/unpack_result_005337$ find . -type f -exec file {} \;
./updater_boot.img: data
./system.img: data
./ramdisk.img: data
./eng_system.img: Linux rev 1.0 ext2 filesystem data, UUID=15eb9b2b-ffde-440b-91f3-1189239a5a14 (extents) (64bit) (large files) (huge files)
./sys_prod.img: data
./fw_dtb.img: data
./bl2.img: data
./patch.img: Linux rev 1.0 ext2 filesystem data, UUID=8786d109-9f39-4396-9298-685ac9682020 (extents) (64bit) (large files) (huge files)
./modem_patch_nv.img: data
./sensorhub.img: data
./dtbo.img: data
./thee.img: data
./updater_vendor_bak.img: data
./npu.img: data
./teeos.img: data
./updater_ramdisk_bak.img: data
./modem_driver.img: Linux rev 1.0 ext2 filesystem data, UUID=afaa6172-53d5-43f1-ae48-48cbe720f0e8 (extents) (64bit) (large files) (huge files)
./modem_vendor.img: Linux rev 1.0 ext2 filesystem data, UUID=16d2447b-8a30-49ba-97fd-a5e83edc480e (extents) (64bit) (large files) (huge files)
./sensorhub_log_dic.img: data
./lowpower_para.img: data
./update_rvt.img: data
./vendor.img: data
./fw_hifi.img: data
./tzsp.img: data
./chip_prod.img: data
./modemnvm_update.img: Linux rev 1.0 ext4 filesystem data, UUID=ce99276b-0957-4206-88f1-a2ce938e7872 (extents) (64bit) (large files) (huge files)
./ptable.img: DOS/MBR boot sector; partition 1 : ID=0xee, start-CHS (0x3ff,255,63), end-CHS (0x3ff,255,63), startsector 1, 0 sectors, extended partition table (last)
./hhee.img: data
./updater_boot_bak.img: data
./kpatch.img: data
./permission_hash_bin.img: data
./modemnvm_cust.img: Linux rev 1.0 ext4 filesystem data, UUID=83a00696-e4e1-4736-bd92-44f7deae6474 (extents) (64bit) (large files) (huge files)
./fw_ufsdev.img: data
./updater_ramdisk.img: data
./trustfirmware.img: data
./eng_chipset.img: Linux rev 1.0 ext2 filesystem data, UUID=75519be4-0418-400e-84da-e0ce3ed3098b (extents) (64bit) (large files) (huge files)
./fw_lpm3.img: data
./update_bak_rvt.img: data
./modem_fw.img: Linux rev 1.0 ext4 filesystem data, UUID=c4e510cd-8874-446b-a6c6-1e9263014425 (extents) (64bit) (large files) (huge files)
./dacc.img: data
./fw_cpu_lpctrl.img: data
./fastboot.img: data
./rvt.img: data
./updater_vendor.img: data
./fw_gpu_lpctrl.img: data
./boot.img: data
./isp_firmware.img: data
./BOARD.list: ASCII text, with CRLF line terminators
./fw_ddr_lpctrl.img: data
./package_info.img: ASCII text
./xloader.img: data


挂载结果：
 sudo mount -o ro,loop system.img system
NTFS signature is missing.
Failed to mount '/dev/loop12': 无效的参数
The device '/dev/loop12' doesn't seem to have a valid NTFS.
Maybe the wrong device is used? Or the whole disk instead of a
partition (e.g. /dev/sda, not /dev/sda1)? Or the other way around?

**Comment by lixianHexin** [comment]
大佬 这边用ubuntu挂载试了下，还是有点问题。
大佬  能挂载的 system.img  能上传下吗？或者 解析好的 华为应用市场 hap 能发下我吗？多谢大佬

**Comment by wuxianlin** [comment]
手机的img？我以为是模拟器的，模拟器的是ext4，手机的是erofs，sudo mount -o loop,ro -t erofs system.img system

**Comment by lixianHexin** [comment]
多谢，使用上面命令后 已解决问题

**Comment by revercc** [comment]
使用 erofs-utils 工具的 fsck.erofs --extract=./output system.img 命令可以直接提取
